/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
 * Generated on: 13-Apr-2022 19:49:01
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 3
 * Denominator Length  : 3
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2020a.app/extern/include/tmwtypes.h 
 */
const int NL = 3;
const real64_T NUM[3] = {
     0.2452372752528,   0.2452372752528,                 0
};
const int DL = 3;
const real64_T DEN[3] = {
                   1,  -0.5095254494944,                 0
};
