/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
 * Generated on: 06-Apr-2022 22:01:24
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form I
 * Numerator Length    : 6
 * Denominator Length  : 6
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2020a.app/extern/include/tmwtypes.h 
 */
const int NL = 6;
const real64_T NUM[6] = {
  2.139615203814e-05,0.0001069807601907,0.0002139615203814,0.0002139615203814,
  0.0001069807601907,2.139615203814e-05
};
const int DL = 6;
const real64_T DEN[6] = {
                   1,   -4.187300047864,    7.069722752792,   -6.009958148187,
      2.570429302524,  -0.4422091823996
};
